### ISSUE TITLE
Visual studio issue

### ISSUE THREAD

**Issue by PavelA85** [wallabyjs/wallaby-angular-controller-sample#1]
Hi,
I've created fork and introduced Visual Studio solution
https://github.com/PavelAgejkin/wallaby-angular-controller-sample
But I have no luck run Wallaby, I get :

```
wallaby.js started
core v1.0.79

​​​​​ReferenceError: Can't find variable: angular
        at js/app.js:1
TypeError: 'undefined' is not an object (evaluating 'App.controller')
        at js/controllers/videoListController.js:7
ReferenceError: Can't find variable: module
        at test/unit/videoListControllerSpec.js:5

Finished executing 0 affected test(s)
```

What I've done:
clone repo >  create empty VS Web ASP application > npm install > run Wallaby from context menu

What I'm doing wrong?
I've tried same scenario for this repo https://github.com/wallabyjs/wallaby-angular-todomvc-sample but still no luck
This solution https://github.com/wallabyjs/public works OK

**Comment by ArtemGovorov** [comment]
Hi, 

try including `node_modules` and its files into the solution. There's a requirement currently that all files that are listed in the `files`/`tests` lists have to be in the solution.

Let me know if it works for you.

**Comment by PavelA85** [comment]
yes, it worked like a charm :+1:
